# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OpenVPN Client
version: "0.0.2"
slug: openvpn-client
description: Connect to OpenVPN server from Home Assistant
url: "https://github.com/kszonek/home-assistant-openvpn-client/tree/master/openvpn-client"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - homeassistant/openvpn-client:rw
options:
  message: "Hello world... changed"
schema:
  message: "str?"
#image: "ghcr.io/kszonek/{arch}-home-assistant-openvpn-client"
