# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "0.0.1"
slug: openvpn-client
description: OpenVPN Client add-on
url: "https://github.com/kszonek/home-assistant-openvpn-client/tree/master/openvpn-client"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/kszonek/{arch}-home-assistant-openvpn-client"
